spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pricingdb
    username: pricing
    password: pricing
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate   # Flyway p/ criar/alterar tabelas
    properties:
      hibernate:
        format_sql: true
        jdbc.lob.non_contextual_creation: true

  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: 8080
